config/routes.rb
Rails.application.routes.draw do
  get 'services/index'

  resources :services
  
  root 'services#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/service.rb
class Service < ApplicationRecord
  validates :base_cost, presence: true, numericality: { only_integer: true }
                      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def show
    @service = Service.find(params[:id]);
  end

  def new
    @service = Service.new
  end

  def edit
    @service = Service.find(params[:id])
  end

  def index
    @services = Service.all
  end
  
  def create
    @service = Service.new(service_params)

    if @service.save
      redirect_to @service
    else 
      render 'new'
    end
  end

  def update
    @service = Service.find(params[:id])

    if @service.update(service_params)
      redirect_to @service
    else
      render 'edit'
    end
  end

  private
    def service_params
      params.require(:service).permit(:name, :base_cost)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/services/edit.html.erb
<h1>Edit a service</h1>

<%= form_with(model: @service, local: true) do |form| %>
  <% if @service.errors.any? %>
    <%= pluralize(@service.errors.count, "error") %> prohibited this article from being saved:
    <% @service.errors.full_messages.each do |message| %>
      <p>
        Error: <%= message %>
      </p>
    <% end%>
  <% end %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :base_cost %><br>
    <%= form.text_field :base_cost %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/services/index.html.erb
<h1>Services</h1>

<%= link_to 'New Service', new_service_path %>

<% @services.each do |service| %>
  <p>
    Service: <%= link_to service.name, service_path(service) %>
    <br>
    Base Cost: <%= service.base_cost %>
  </p>
<% end %>

app/views/services/new.html.erb
<h1>Add a service</h1>

<%= form_with scope: :service, url: services_path, local: true do |form| %>
  <% if @service.errors.any? %>
    <%= pluralize(@service.errors.count, "error") %> prohibited this article from being saved:
    <% @service.errors.full_messages.each do |message| %>
      <p>
        Error: <%= message %>
      </p>
    <% end%>
  <% end %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :base_cost %><br>
    <%= form.text_field :base_cost %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/services/show.html.erb
<%= link_to 'Services', services_path %>

</br>

<%= link_to 'Edit', edit_service_path %>

<p>
  <strong>Name</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Base Cost</strong>
  <%= @service.base_cost %>
</p>